name: GitHub Pages

on:
  push:
    branches:
      - main  # Triggers deployment when pushing to main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Ensures submodules are checked out, important for Hugo themes
          fetch-depth: 0    # Fetches all history needed for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'  # Specifies Hugo version to ensure consistent builds

      - name: Build
        run: hugo --minify  # Builds the site with minification

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public